import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { DashboardLayout } from '@/components/layout/DashboardLayout';
import { 
  subscribeToLiveStreams, 
  createLiveStream, 
  updateStreamViewerCount, 
  endLiveStream,
  getAgoraConfig,
  type LiveStream 
} from '@/lib/agoraService';
import { 
  Video, 
  VideoOff, 
  Mic, 
  MicOff, 
  Users, 
  Eye, 
  Coins, 
  Gift, 
  MoreVertical,
  Play,
  Square,
  Settings
} from 'lucide-react';
import { useLanguage } from '@/lib/i18n';
import { 
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger
} from '@/components/ui/dropdown-menu';
import { Switch } from '@/components/ui/switch';

const LiveStreaming = () => {
  const { t, isRTL } = useLanguage();
  const [liveStreams, setLiveStreams] = useState<LiveStream[]>([]);
  const [loading, setLoading] = useState(true);
  const [agoraConfig, setAgoraConfig] = useState<any>(null);
  const [selectedStream, setSelectedStream] = useState<LiveStream | null>(null);
  const [isCreatingStream, setIsCreatingStream] = useState(false);
  const [newStreamData, setNewStreamData] = useState({
    hostId: 'demo_host',
    hostName: 'Demo Host',
    hostImage: 'https://picsum.photos/seed/100?img=1',
    title: '',
    category: 'entertainment',
    settings: {
      allowGuests: true,
      maxViewers: 1000,
      recordStream: false
    }
  });

  useEffect(() => {
    const fetchConfig = async () => {
      const config = await getAgoraConfig();
      setAgoraConfig(config);
    };

    fetchConfig();

    // Subscribe to live streams
    const unsubscribe = subscribeToLiveStreams((streams) => {
      setLiveStreams(streams);
      setLoading(false);
    });

    return () => unsubscribe();
  }, []);

  const handleCreateStream = async () => {
    if (!newStreamData.title.trim()) return;

    try {
      setIsCreatingStream(true);
      const channelName = `channel_${Date.now()}`;
      
      const streamData = {
        ...newStreamData,
        channelName,
        agoraToken: '', // Will be generated by backend
        startTime: new Date(),
        status: 'live' as 'live'
      };

      const streamId = await createLiveStream(streamData);
      
      // Reset form
      setNewStreamData({
        ...newStreamData,
        title: ''
      });
      
      // Show success message
      console.log('Stream created successfully:', streamId);
    } catch (error) {
      console.error('Error creating stream:', error);
    } finally {
      setIsCreatingStream(false);
    }
  };

  const handleEndStream = async (streamId: string) => {
    try {
      await endLiveStream(streamId);
      console.log('Stream ended successfully');
    } catch (error) {
      console.error('Error ending stream:', error);
    }
  };

  const formatDuration = (startTime: any, endTime?: any) => {
    const start = startTime?.toDate?.() || new Date(startTime);
    const end = endTime?.toDate?.() || new Date();
    const duration = Math.floor((end.getTime() - start.getTime()) / 1000);
    
    const hours = Math.floor(duration / 3600);
    const minutes = Math.floor((duration % 3600) / 60);
    const seconds = duration % 60;
    
    return `${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}`;
  };

  const formatNumber = (num: number) => {
    if (num >= 1000000) return (num / 1000000).toFixed(1) + 'M';
    if (num >= 1000) return (num / 1000).toFixed(1) + 'K';
    return num.toString();
  };

  if (loading) {
    return (
      <DashboardLayout>
        <div className="flex items-center justify-center min-h-screen">
          <div className="animate-spin rounded-full h-12 w-12 border-4 border-primary border-t-transparent"></div>
        </div>
      </DashboardLayout>
    );
  }

  return (
    <DashboardLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-foreground">Live Streaming</h1>
            <p className="text-muted-foreground">Manage live streams and video calls</p>
          </div>
          <div className="flex items-center gap-2">
            <Badge variant={agoraConfig?.appId ? "default" : "secondary"}>
              {agoraConfig?.appId ? "Agora Connected" : "Agora Not Configured"}
            </Badge>
          </div>
        </div>

        {/* Create Stream Form */}
        <Card>
          <CardHeader>
            <CardTitle>Create New Stream</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <input
                type="text"
                placeholder="Stream title"
                value={newStreamData.title}
                onChange={(e) => setNewStreamData({...newStreamData, title: e.target.value})}
                className="px-4 py-2 border rounded-lg bg-background border-border text-foreground"
              />
              <select
                value={newStreamData.category}
                onChange={(e) => setNewStreamData({...newStreamData, category: e.target.value})}
                className="px-4 py-2 border rounded-lg bg-background border-border text-foreground"
              >
                <option value="entertainment">Entertainment</option>
                <option value="gaming">Gaming</option>
                <option value="music">Music</option>
                <option value="education">Education</option>
                <option value="sports">Sports</option>
              </select>
              <div className="flex items-center gap-2">
                <Switch 
                  checked={newStreamData.settings.allowGuests}
                  onCheckedChange={(checked) => setNewStreamData({
                    ...newStreamData,
                    settings: {...newStreamData.settings, allowGuests: checked}
                  })}
                />
                <span className="text-sm">Allow Guests</span>
              </div>
              <Button 
                onClick={handleCreateStream}
                disabled={!newStreamData.title.trim() || isCreatingStream}
                className="bg-primary hover:bg-primary/90"
              >
                {isCreatingStream ? 'Creating...' : 'Start Stream'}
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Live Streams Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-2 xl:grid-cols-3 gap-6">
          {liveStreams.map((stream) => (
            <Card key={stream.id} className="overflow-hidden">
              <div className="relative">
                {/* Stream Preview */}
                <div className="aspect-video bg-gradient-to-br from-purple-600 to-pink-600 flex items-center justify-center">
                  <div className="text-center text-white">
                    <Video className="w-16 h-16 mx-auto mb-2" />
                    <p className="font-semibold">{stream.title}</p>
                  </div>
                </div>
                
                {/* Live Badge */}
                <div className="absolute top-2 left-2">
                  <Badge variant="destructive" className="bg-red-500">
                    <div className="w-2 h-2 bg-white rounded-full mr-2 animate-pulse"></div>
                    LIVE
                  </Badge>
                </div>

                {/* Viewer Count */}
                <div className="absolute top-2 right-2 bg-black/50 text-white px-2 py-1 rounded flex items-center gap-1">
                  <Eye className="w-4 h-4" />
                  <span className="text-sm">{formatNumber(stream.viewerCount)}</span>
                </div>
              </div>

              <CardContent className="p-4">
                {/* Stream Info */}
                <div className="flex items-center gap-3 mb-3">
                  <Avatar className="w-10 h-10">
                    <AvatarImage src={stream.hostImage} />
                    <AvatarFallback>{stream.hostName[0]}</AvatarFallback>
                  </Avatar>
                  <div className="flex-1">
                    <h3 className="font-semibold text-foreground">{stream.hostName}</h3>
                    <p className="text-sm text-muted-foreground">{stream.category}</p>
                  </div>
                </div>

                {/* Stream Stats */}
                <div className="grid grid-cols-3 gap-2 mb-3">
                  <div className="text-center">
                    <div className="text-lg font-bold text-foreground">{formatNumber(stream.viewerCount)}</div>
                    <div className="text-xs text-muted-foreground">Viewers</div>
                  </div>
                  <div className="text-center">
                    <div className="text-lg font-bold text-foreground">{formatNumber(stream.coinsEarned)}</div>
                    <div className="text-xs text-muted-foreground">Coins</div>
                  </div>
                  <div className="text-center">
                    <div className="text-lg font-bold text-foreground">{stream.giftsReceived}</div>
                    <div className="text-xs text-muted-foreground">Gifts</div>
                  </div>
                </div>

                {/* Duration */}
                <div className="text-sm text-muted-foreground mb-3">
                  Duration: {formatDuration(stream.startTime)}
                </div>

                {/* Actions */}
                <div className="flex items-center gap-2">
                  <Button size="sm" variant="outline" className="flex-1">
                    <Play className="w-4 h-4 mr-1" />
                    Watch
                  </Button>
                  <Button 
                    size="sm" 
                    variant="destructive"
                    onClick={() => handleEndStream(stream.id)}
                  >
                    <Square className="w-4 h-4 mr-1" />
                    End
                  </Button>
                  <DropdownMenu>
                    <DropdownMenuTrigger asChild>
                      <Button size="sm" variant="ghost">
                        <MoreVertical className="w-4 h-4" />
                      </Button>
                    </DropdownMenuTrigger>
                    <DropdownMenuContent>
                      <DropdownMenuItem>
                        <Settings className="w-4 h-4 mr-2" />
                        Settings
                      </DropdownMenuItem>
                      <DropdownMenuItem>
                        <Gift className="w-4 h-4 mr-2" />
                        Send Gift
                      </DropdownMenuItem>
                    </DropdownMenuContent>
                  </DropdownMenu>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Empty State */}
        {liveStreams.length === 0 && (
          <Card>
            <CardContent className="text-center py-12">
              <Video className="w-16 h-16 mx-auto mb-4 text-muted-foreground" />
              <h3 className="text-lg font-semibold text-foreground mb-2">No Live Streams</h3>
              <p className="text-muted-foreground mb-4">Start your first live stream to see it here</p>
              <Button onClick={() => setNewStreamData({...newStreamData, title: 'My First Stream'})}>
                <Video className="w-4 h-4 mr-2" />
                Start Streaming
              </Button>
            </CardContent>
          </Card>
        )}
      </div>
    </DashboardLayout>
  );
};

export default LiveStreaming;
